import type { Metadata, Viewport } from "next";
import { Press_Start_2P, Silkscreen, VT323 } from "next/font/google";
import { Sky } from "@/components/Sky";
import "./globals.css";

const press = Press_Start_2P({ weight: "400", subsets: ["latin"], variable: "--font-press" });
const silk = Silkscreen({ weight: ["400", "700"], subsets: ["latin"], variable: "--font-silk" });
const vt = VT323({ weight: "400", subsets: ["latin"], variable: "--font-vt" });

// iOS launch screens, generated by scripts/icons.py: [css width, css height, pixel ratio]
const SPLASH = [
  [440, 956, 3], [402, 874, 3], [420, 912, 3], [430, 932, 3], [393, 852, 3],
  [428, 926, 3], [390, 844, 3], [375, 812, 3], [414, 896, 2], [375, 667, 2],
] as const;

export const metadata: Metadata = {
  title: "Habit Tower",
  description: "A pixel-art habit tracker. One floor per habit.",
  applicationName: "Habit Tower",
  appleWebApp: {
    capable: true,
    title: "Habits",
    statusBarStyle: "black-translucent",
    startupImage: SPLASH.map(([w, h, r]) => ({
      url: `/splash/${w * r}x${h * r}.png`,
      media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait)`,
    })),
  },
};

export const viewport: Viewport = {
  themeColor: "#070b24",
  viewportFit: "cover",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${press.variable} ${silk.variable} ${vt.variable}`}>
      <body>
        <Sky />
        {children}
      </body>
    </html>
  );
}
